name: Enforce Squashed Commit Message Structure

on:
  pull_request:
    types:
      - closed

jobs:
  commit-message-enforcement:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract squashed commit message
        id: extract-message
        run: |
          # Retrieve the merge commit SHA
          MERGE_COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          # Fetch the merge commit message
          MERGE_COMMIT_MSG=$(git log --format=%B -n 1 $MERGE_COMMIT_SHA)

          squashed_message=$(git log --pretty=format:%s -n 1 $MERGE_COMMIT_SHA)
          echo "::set-output name=message::$squashed_message"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Validate squashed commit message
        uses: actions/github-script@v5
        id: validate-commit-message
        if: !echo ${{ steps.extract-message.outputs.message }}' | npx commitlint

        with:
          script: |
            echo "Commit message does not adhere to the convention."
            # Revert the merge commit using the GitHub API
            PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
            REPO_API_URL=$(jq -r '.repository.url' $GITHUB_EVENT_PATH)
            AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
            REVERT_COMMIT_SHA=$(git log --format=%H -n 2 | tail -1)
            # Revert the merge commit
            await execSync(`curl -X POST -H "$AUTH_HEADER" "$REPO_API_URL/pulls/$PR_NUMBER/revert" -d "{\"sha\":\"$REVERT_COMMIT_SHA\"}"`)
            # Reopen the pull reque